// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaYpWxn1qeqiWxYjNd6IrpcFOZjj0cEFY',
    appId: '1:739898413148:web:ac02fa79d35c3489f05699',
    messagingSenderId: '739898413148',
    projectId: 'withme-7e569',
    authDomain: 'withme-7e569.firebaseapp.com',
    storageBucket: 'withme-7e569.firebasestorage.app',
    measurementId: 'G-HR1Y9MJBEG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1ue8cNSHhupZCaM5WCeo-dW__PmBLgqY',
    appId: '1:551869451781:android:8b1635968d8657041c966c',
    messagingSenderId: '551869451781',
    projectId: 'withme-7e569',
    storageBucket: 'withme-7e569.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq_tUC6xR0lARIugEdM8I3BhhH4dF3t6Y',
    appId: '1:551869451781:ios:584351463c392e561c966c',
    messagingSenderId: '551869451781',
    projectId: 'withme-7e569',
    storageBucket: 'withme-7e569.firebasestorage.app',
    iosClientId: '551869451781-cm473tkbhr1rnti7q1rgt54gb0po1nqj.apps.googleusercontent.com',
    iosBundleId: 'com.example.withMe',
  );
}
